### ISSUE TITLE
Recolecta de Hormigas en Campo.

### ISSUE THREAD

**Issue by BidelkisCastillo** [biogeografia-201902/unidad-0-asignacion-4-practica-campo-material-y-odk-BidelkisCastillo#1]
Buen día @geofis  acabo de ver su e-mail, ya le envié los formularios de mi recolecta.
Realice algunas el sábado pero la noche antes había llovido y no encontré muchas en pavimento mientras que en suelo siempre hay pero son difíciles de agarrar.
Mañana llevaré las muestras que he tomado.

**Comment by geofis** [comment]
Bien, veamos qué conseguiste. No es bueno colectar en día de lluvia, pero si es lluvia de noche anterior, no suele afectar

**Comment by BidelkisCastillo** [comment]
Esta bien, en suelo si habían muchas pero en pavimento es que eran pocas. Pero las revisamos mañana.
